# Generated by Django 4.2.7 on 2025-03-11 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('message_type', models.CharField(choices=[('confirmation', 'Confirmação de Agendamento'), ('reminder', 'Lembrete'), ('thank_you', 'Agradecimento'), ('custom', 'Personalizada')], default='custom', max_length=20, verbose_name='Tipo de mensagem')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Modelo de mensagem',
                'verbose_name_plural': 'Modelos de mensagens',
            },
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'E-mail'), ('call', 'Ligação')], max_length=10, verbose_name='Canal')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='appointments.appointment', verbose_name='Agendamento')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='communications.messagetemplate', verbose_name='Modelo de mensagem')),
            ],
            options={
                'verbose_name': 'Mensagem enviada',
                'verbose_name_plural': 'Mensagens enviadas',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.IntegerField(choices=[(1, '1 dia antes'), (2, '2 dias antes'), (3, '3 dias antes')], default=1, verbose_name='Dias antes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='communications.messagetemplate', verbose_name='Modelo de mensagem')),
            ],
            options={
                'verbose_name': 'Configuração de lembrete',
                'verbose_name_plural': 'Configurações de lembretes',
                'unique_together': {('template', 'days_before')},
            },
        ),
    ]
