# Generated by Django 4.2.7 on 2025-03-12 11:29

import clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, validators=[clients.models.Client.validate_phone_number], verbose_name='Telefone'),
        ),
    ]
